version: '3.8'

services:
  # Base de données PostgreSQL
  servicedating.db:
    image: 'postgres:latest'
    env_file: ./webApp/back.env
    ports:
      - '5432:5432'
    volumes:
      - ./webApp/app/sql:/var/sql
    restart: always

  # Service Administration des bases SQL (Adminer)
  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'

  # Backend Symfony API
  servicedating.backend:
    build:
      context: ./
      dockerfile: ./webApp/build/Dockerfile.backend
    container_name: servicedating-backend
    volumes:
      - ./webApp:/var/www/html
    ports:
      - "8889:8000"
    command: symfony server:start --no-tls --port=8000 --allow-http --no-interaction --ansi --listen-ip=0.0.0.0
    depends_on:
      - servicedating.db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@servicedating.db:5432/${POSTGRES_DB:-ccd}
    restart: always

  # Service OptiApp Java
  optiapp:
    build:
      context: ./optiApp/build
    container_name: optiapp
    volumes:
      - ./optiApp:/usr/src/app
    ports:
      - "8090:8080"
    depends_on:
      - servicedating.db
    command: ["tail", "-f", "/dev/null"]

