security:
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: login
                check_path: login
                username_parameter: _username
                password_parameter: _password
                default_target_path: index
                enable_csrf: true
            logout:
                path: logout
                target: login

#    access_control:
#        - { path: ^/login, roles: PUBLIC_ACCESS }
#        - { path: ^/register, roles: PUBLIC_ACCESS }
#        - { path: ^/, roles: ROLE_USER }