services:
  # Base de données PostgreSQL
  servicedating.db:
    image: 'postgres:latest'
    env_file: ./ccd_db.env
    ports:
      - '5432:5432'
    volumes:
      - ./webApp/app/sql:/var/sql
    restart: always

  # Service Administration des bases SQL (Adminer)
  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'

  # Backend Symfony API
  servicedating.backend:
    build:
      context: ./webApp
      dockerfile: ./webApp/build/DockerFile.backend
    container_name: servicedating-backend
    ports:
      - "8889:8000"
    command: symfony server:start --no-tls --port=8000 --allow-http --no-interaction --ansi --listen-ip=0.0.0.0
    volumes:
      - ./webApp/cvpsenergy.api:/var/www/html
    depends_on:
      - servicedating.db
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-root}@servicedating.db:5432/${POSTGRES_DB:-cvps}
    restart: always
